# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
StoryGenre.destroy_all
Story.destroy_all
Genre.destroy_all
Comment.destroy_all

u1 = User.create(username:"Adam", password:"rose", penname:"ClimberGuy", bio:"I am a cool climber guy. I like to go climbing.", picture:"", email:"Coolclimber@awesome.com")
u2 = User.create(username:"Ix", password:"rose", penname:"CoolCat", bio:"I am a cool cat. Cats are the coolest and the one named Rose is the best of all cats.", picture:"", email: "Catperson@catpeople.com")
u3 = User.create(username:"Davis", password:"rose", penname:"CoolGuy", bio:"I am a cool guy. I am the coolest guy", picture:"", email:"Coolguy@allcoolguys.com")

g1 = Genre.create(genre:"Action and Adventure")
g2 = Genre.create(genre:"Alternate History")
g3 = Genre.create(genre:"Anthology")
g4 = Genre.create(genre:"Chick Literature")
g5 = Genre.create(genre:"Children's Literature")
g6 = Genre.create(genre:"Classic")
g7 = Genre.create(genre:"Comic Book")
g8 = Genre.create(genre:"Coming-Of-Age")
g9 = Genre.create(genre:"Crime")
g10 = Genre.create(genre:"Drama")
g11 = Genre.create(genre:"New Fairtytale")
g12 = Genre.create(genre:"Fantasy")
g13 = Genre.create(genre:"New Folktale")
g14 = Genre.create(genre:"Gothic Fiction")
g15 = Genre.create(genre:"Graphic Novel")
g16 = Genre.create(genre:"Historical Fiction")
g17 = Genre.create(genre:"Horror")
g18 = Genre.create(genre:"Humor")
g19 = Genre.create(genre:"Legend")
g20 = Genre.create(genre:"Magical Realism")
g21 = Genre.create(genre:"Meta Fiction")
g22 = Genre.create(genre:"Mystery")
g23 = Genre.create(genre:"Mythology")
g24 = Genre.create(genre:"Mythopoeia")
g25 = Genre.create(genre:"Paranormal")
g26 = Genre.create(genre:"Picture Book")
g27 = Genre.create(genre:"Poetry")
g28 = Genre.create(genre:"Political Thriller")
g29 = Genre.create(genre:"Realistic Fiction")
g30 = Genre.create(genre:"Romance")
g31 = Genre.create(genre:"Satire")
g32 = Genre.create(genre:"Science Fiction")
g33 = Genre.create(genre:"Spy Fiction")
g34 = Genre.create(genre:"Superhero")
g35 = Genre.create(genre:"Suspense")
g36 = Genre.create(genre:"Swashbuckler")
g37 = Genre.create(genre:"Tall Tale")
g38 = Genre.create(genre:"Theological Fiction")
g39 = Genre.create(genre:"Thriller")
g40 = Genre.create(genre:"Tragedy")
g41 = Genre.create(genre:"Tragic Comedy")
g42 = Genre.create(genre:"Travel")
g43 = Genre.create(genre:"Suspense")
g44 = Genre.create(genre:"Western")
g45 = Genre.create(genre:"Young Adult")

s1 = Story.create(title:"Hello World", content:"Hello World", reads: 10, likes: 10, user_id: u1.id)
s2 = Story.create(title:"Hello World", content:"Hello World", reads: 10, likes: 10, user_id: u2.id)
s3 = Story.create(title:"Hello World", content:"Hello World", reads: 10, likes: 10, user_id: u3.id)
s4 = Story.create(title:"Hello World2", content:"Hello World", reads: 10, likes: 10, user_id: u1.id)
s5 = Story.create(title:"Hello World2", content:"Hello World", reads: 10, likes: 10, user_id: u2.id)
s6 = Story.create(title:"Hello World2", content:"Hello World", reads: 10, likes: 10, user_id: u3.id)
s7 = Story.create(title:"Hello World3", content:"Hello World", reads: 10, likes: 10, user_id: u1.id)
s8 = Story.create(title:"Hello World3", content:"Hello World", reads: 10, likes: 10, user_id: u2.id)
s9 = Story.create(title:"Hello World3", content:"Hello World", reads: 10, likes: 10, user_id: u3.id)

s1g1 = StoryGenre.create(story_id: s1.id, genre_id: g44.id)
s1g2 = StoryGenre.create(story_id: s1.id, genre_id: g43.id)
s1g3 = StoryGenre.create(story_id: s1.id, genre_id: g2.id)
s2g1 = StoryGenre.create(story_id: s2.id, genre_id: g1.id)
s2g2 = StoryGenre.create(story_id: s2.id, genre_id: g5.id)
s2g3 = StoryGenre.create(story_id: s2.id, genre_id: g6.id)
s3g1 = StoryGenre.create(story_id: s3.id, genre_id: g10.id)
s3g2 = StoryGenre.create(story_id: s3.id, genre_id: g12.id)
s3g3 = StoryGenre.create(story_id: s3.id, genre_id: g15.id)
s4g1 = StoryGenre.create(story_id: s4.id, genre_id: g18.id)
s4g2 = StoryGenre.create(story_id: s4.id, genre_id: g22.id)
s5g1 = StoryGenre.create(story_id: s5.id, genre_id: g24.id)
s5g2 = StoryGenre.create(story_id: s5.id, genre_id: g26.id)
s6g1 = StoryGenre.create(story_id: s6.id, genre_id: g28.id)
s6g2 = StoryGenre.create(story_id: s6.id, genre_id: g32.id)
s7g1 = StoryGenre.create(story_id: s7.id, genre_id: g34.id)
s8g1 = StoryGenre.create(story_id: s8.id, genre_id: g36.id)
s9g1 = StoryGenre.create(story_id: s9.id, genre_id: g39.id)

c1 = Comment.create(content:"Adam's Awesome Comment!", user_id: u1.id, story_id: s1.id)
c2 = Comment.create(content:"Ix's Awesome Comment!", user_id: u2.id, story_id: s2.id)
c3 = Comment.create(content:"Davis' Awesome Comment!", user_id: u3.id, story_id: s3.id)
c4 = Comment.create(content:"Adam's Awesome Comment!", user_id: u1.id, story_id: s4.id)
c5 = Comment.create(content:"Ix's Awesome Comment!", user_id: u2.id, story_id: s5.id)
c6 = Comment.create(content:"Davis' Awesome Comment!", user_id: u3.id, story_id: s6.id)
c7 = Comment.create(content:"Adam's Awesome Comment!", user_id: u1.id, story_id: s7.id)
c8 = Comment.create(content:"Ix's Awesome Comment!", user_id: u2.id, story_id: s8.id)
c9 = Comment.create(content:"Davis' Awesome Comment!", user_id: u3.id, story_id: s9.id)
c10 = Comment.create(content:"Adam's Awesome Comment!", user_id: u1.id, story_id: s1.id)
c11 = Comment.create(content:"Ix's Awesome Comment!", user_id: u2.id, story_id: s2.id)
c12 = Comment.create(content:"Davis' Awesome Comment!", user_id: u3.id, story_id: s3.id)
c13 = Comment.create(content:"Adam's Awesome Comment!", user_id: u1.id, story_id: s4.id)
c14 = Comment.create(content:"Ix's Awesome Comment!", user_id: u2.id, story_id: s5.id)
c15 = Comment.create(content:"Davis' Awesome Comment!", user_id: u3.id, story_id: s6.id)
c16 = Comment.create(content:"Adam's Awesome Comment!", user_id: u1.id, story_id: s7.id)
c17 = Comment.create(content:"Ix's Awesome Comment!", user_id: u2.id, story_id: s8.id)
c18 = Comment.create(content:"Davis' Awesome Comment!", user_id: u3.id, story_id: s9.id)